-- intel-agent schema
-- PostgreSQL 16

CREATE TABLE IF NOT EXISTS sources (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,          -- 'hackernews', 'github', 'arxiv', etc.
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    last_run    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
    id          SERIAL PRIMARY KEY,
    source_id   INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    external_id TEXT NOT NULL,                 -- id from the source, e.g. HackerNews item id, GitHub repo full name, arXiv paper id
    title       TEXT NOT NULL,
    url         TEXT,
    description TEXT,
    -- fields below are generated by the LLM during processing
    summary     JSONB,                         -- ["bullet 1", "bullet 2", "bullet 3"]
    category    TEXT,                          -- tech-ai, tech-frontend, tech-infra, tech-other, gaming, music, film-tv
    tags        JSONB,                         -- ["tag1", "tag2"]
    processed   BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_source_item UNIQUE (source_id, external_id)
);

CREATE TABLE IF NOT EXISTS digests (
    id           SERIAL PRIMARY KEY,
    date         DATE NOT NULL UNIQUE,
    content      JSONB NOT NULL,               -- structured content for the digest
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_items_source      ON items (source_id);
CREATE INDEX IF NOT EXISTS idx_items_category    ON items (category);
CREATE INDEX IF NOT EXISTS idx_items_processed   ON items (processed);
CREATE INDEX IF NOT EXISTS idx_items_collected   ON items (collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_items_published   ON items (published_at DESC);
